CREATE DATABASE vbass;

CREATE TABLE vbass.LOGIN
( 
	USERNAME VARCHAR(30),
	PASSWORD VARCHAR(30),
	ROLE VARCHAR(3)
)
;

CREATE TABLE vbass.ENTITY
( ENTITY_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
  ENTITY_NAME VARCHAR(30),
  ENT_ATTR1	VARCHAR(10),
  ENT_ATTR2	VARCHAR(10),
  ENT_ATTR3	VARCHAR(10),
  ENT_ATTR4	VARCHAR(10),
  ENT_ATTR5	VARCHAR(10),
  ENT_BILL_CATG VARCHAR(10),
  ENT_VR_NR MEDIUMINT  ,
  PRIMARY KEY (ENTITY_ID)
);



CREATE TABLE vbass.ENTITY_ATTRIB_MAP
(
ENTITY_ID MEDIUMINT,
ENT_ATTR1_ID MEDIUMINT,
ENT_ATTR2_ID MEDIUMINT,
ENT_ATTR3_ID MEDIUMINT,
ENT_ATTR4_ID MEDIUMINT,
ENT_ATTR5_ID MEDIUMINT
);

CREATE TABLE vbass.ENTITY_PROD
( 
  ENT_PROD_ID MEDIUMINT NOT NULL AUTO_INCREMENT,  
  ENT_PROD_NAME VARCHAR(30),
  ENT_VR_NR MEDIUMINT,
  PRIMARY KEY (ENT_PROD_ID)
);

CREATE TABLE vbass.ENTITY_PROD_RULE
( 
  ENT_RULE_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
  ENT_PROD_ID MEDIUMINT,
  ENTITY_ID MEDIUMINT,
  ENT_CHG_TYPE VARCHAR(4),
  ENT_PRORATE TINYINT,  
  ENT_AMT DECIMAL(4,2),  
  ENT_TX_PER DECIMAL(4,2),
  ENT_VR_NR MEDIUMINT,
  PRIMARY KEY (ENT_RULE_ID)
);

CREATE TABLE vbass.VERSION
(
	ENT_VR_NR MEDIUMINT NOT NULL AUTO_INCREMENT,
	ENT_VR_CATG VARCHAR(2),
	ENT_PREV_VR_NR MEDIUMINT,
	INST_CTG VARCHAR(4),
	PRIMARY KEY (ENT_VR_NR)
);

CREATE TABLE vbass.ENT_INST_TR
( ENT_INST_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
  ENTITY_ID MEDIUMINT,
  ENT_INS_NAME VARCHAR(30),  
  ENT_INST_ATTR1	VARCHAR(10),
  ENT_INST_ATTR2	VARCHAR(10),
  ENT_INST_ATTR3	VARCHAR(10),
  ENT_INST_ATTR4	VARCHAR(10),
  ENT_INST_ATTR5	VARCHAR(10),
  ADDRESS_ID	MEDIUMINT,
  ENT_INST_ST_DT DATE,
  ENT_INST_ED_DT DATE,
  ENT_INS_STS INT(2),  
  ENT_VR_NR MEDIUMINT,
  PRIMARY KEY (ENT_INST_ID)
);


CREATE TABLE vbass.ENT_INST_PROD_TR
( 
  ENT_PROD_INST_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
  ENT_INST_ID MEDIUMINT, 
  ENT_PROD_ID MEDIUMINT,      
  ENT_INST_ST_DT DATE,
  ENT_INST_ED_DT DATE,
  ENT_PROD_INS_STS INT(2),  
  ENT_VR_NR MEDIUMINT,
  PRIMARY KEY (ENT_PROD_INST_ID)
);

CREATE TABLE vbass.BILL_GEN
( BILL_GEN_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
  ENT_INST_ID MEDIUMINT,  
  BILL_DT DATE,  
  LAST_MOD DATE,
  ENT_VR_NR MEDIUMINT,
  PRIMARY KEY (BILL_GEN_ID)
);

CREATE TABLE vbass.ADDRESS_HISTORY_TR (
    ADDRESS_ID INT(5),
    LINE1 VARCHAR(20) ,
    LINE2  VARCHAR(20) ,
    ZIP_CODE  VARCHAR(10) ,
    STATE VARCHAR(10),
    COUNTRY VARCHAR(10)
 ) ;


CREATE TABLE vbass.REF_MAPPING ( 
ATTRIB_TYPE VARCHAR(50), 
ATTRIB_NAME VARCHAR(20) , 
REF_TYPE_ID INT(10) 
) ;


CREATE TABLE vbass.REFERENCE_CODE
( REF_TYPE_ID INT(10) ,
  REFERENCE_CODE INT(5) ,
  CODE_LABEL VARCHAR(30)
);

CREATE TABLE vbass.BILL_GEN_DET
( TXN_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
  ENT_INST_ID MEDIUMINT,  
  ENT_PROD_INST_ID MEDIUMINT,  
  BILL_GEN_ID MEDIUMINT,
  TXN_DT DATE,
  PERIOD_ST_DT DATE,
  PERIOD_ED_DT DATE,
  TNX_DESC VARCHAR(100),
  TXN_AMT DECIMAL(4,2),
  TAX_AMT DECIMAL(4,2),
  TXN_BASE_AMT DECIMAL(4,2),
  TXN_QTY DECIMAL(4,2),
  PRIMARY KEY (TXN_ID)
);

CREATE TABLE vbass.USG_DET
( USG_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
  ENT_INST_ID MEDIUMINT,  
  ENT_PROD_INST_ID MEDIUMINT, 
  USG_DT DATE,
  USG_DESC VARCHAR(100),
  USG_AMT DECIMAL(4,2),
  USG_QTY DECIMAL(4,2),
  ENT_VR_NR MEDIUMINT,
  PRIMARY KEY (USG_ID)
  
);

INSERT INTO `vbass`.`login` (`USERNAME`, `PASSWORD`, `ROLE`) VALUES ('sridhar', 'vbass1', 'DEV');
INSERT INTO `vbass`.`login` (`USERNAME`, `PASSWORD`, `ROLE`) VALUES ('nishanth', 'vbass2', 'DEV');
INSERT INTO `vbass`.`login` (`USERNAME`, `PASSWORD`, `ROLE`) VALUES ('kiran', 'vbass3', 'DEV');
INSERT INTO `vbass`.`login` (`USERNAME`, `PASSWORD`, `ROLE`) VALUES ('bqa1', 'vbass1', 'BQA');
INSERT INTO `vbass`.`login` (`USERNAME`, `PASSWORD`, `ROLE`) VALUES ('bqa2', 'vbass2', 'BQA');
INSERT INTO `vbass`.`login` (`USERNAME`, `PASSWORD`, `ROLE`) VALUES ('user1', 'prod1', 'PRD');
INSERT INTO `vbass`.`login` (`USERNAME`, `PASSWORD`, `ROLE`) VALUES ('user2', 'prod2', 'PRD');

INSERT INTO `vbass`.`entity` (`ENTITY_ID`, `ENTITY_NAME`, `ENT_ATTR1`, `ENT_ATTR2`, `ENT_ATTR3`, `ENT_ATTR4`, `ENT_ATTR5`, `ENT_BILL_CATG`, `ENT_VR_NR`) VALUES (NULL, 'TSSPower', 'Service No', NULL, NULL, NULL, NULL, 'MON', NULL);
INSERT INTO `vbass`.`entity` (`ENTITY_ID`, `ENTITY_NAME`, `ENT_ATTR1`, `ENT_ATTR2`, `ENT_ATTR3`, `ENT_ATTR4`, `ENT_ATTR5`, `ENT_BILL_CATG`, `ENT_VR_NR`) VALUES (NULL, 'BSNL', 'Domain', NULL, NULL, NULL, NULL, 'MON', NULL);
INSERT INTO `vbass`.`entity` (`ENTITY_ID`, `ENTITY_NAME`, `ENT_ATTR1`, `ENT_ATTR2`, `ENT_ATTR3`, `ENT_ATTR4`, `ENT_ATTR5`, `ENT_BILL_CATG`, `ENT_VR_NR`) VALUES (NULL, 'Cafe Coffee', 'City', NULL, NULL, NULL, NULL, 'IMM', NULL);

INSERT INTO `vbass`.`entity_prod` (`ENT_PROD_ID`, `ENT_PROD_NAME`, `ENT_VR_NR`) VALUES (NULL, 'BTU Units', NULL);
INSERT INTO `vbass`.`entity_prod` (`ENT_PROD_ID`, `ENT_PROD_NAME`, `ENT_VR_NR`) VALUES (NULL, 'Capachino', NULL);
INSERT INTO `vbass`.`entity_prod` (`ENT_PROD_ID`, `ENT_PROD_NAME`, `ENT_VR_NR`) VALUES (NULL, 'Burger', NULL);
INSERT INTO `vbass`.`entity_prod` (`ENT_PROD_ID`, `ENT_PROD_NAME`, `ENT_VR_NR`) VALUES (NULL, 'Mobile 3G', NULL);
INSERT INTO `vbass`.`entity_prod` (`ENT_PROD_ID`, `ENT_PROD_NAME`, `ENT_VR_NR`) VALUES (NULL, 'Plan-180', NULL);
INSERT INTO `vbass`.`entity_prod` (`ENT_PROD_ID`, `ENT_PROD_NAME`, `ENT_VR_NR`) VALUES (NULL, 'Combo-500min', NULL);

INSERT INTO `vbass`.`entity_prod_rule` (`ENT_RULE_ID`, `ENT_PROD_ID`, `ENTITY_ID`, `ENT_CHG_TYPE`, `ENT_PRORATE`, `ENT_AMT`, `ENT_TX_PER`, `ENT_VR_NR`) VALUES (NULL, '1', '1', 'USG', 'NA', '3.54', '14.44', NULL);
INSERT INTO `vbass`.`entity_prod_rule` (`ENT_RULE_ID`, `ENT_PROD_ID`, `ENTITY_ID`, `ENT_CHG_TYPE`, `ENT_PRORATE`, `ENT_AMT`, `ENT_TX_PER`, `ENT_VR_NR`) VALUES (NULL, '2', '3', 'USG', 'NA', '45.00', '14.44', NULL);
INSERT INTO `vbass`.`entity_prod_rule` (`ENT_RULE_ID`, `ENT_PROD_ID`, `ENTITY_ID`, `ENT_CHG_TYPE`, `ENT_PRORATE`, `ENT_AMT`, `ENT_TX_PER`, `ENT_VR_NR`) VALUES (NULL, '3', '3', 'USG', 'NA', '20.00', '14.44', NULL);
INSERT INTO `vbass`.`entity_prod_rule` (`ENT_RULE_ID`, `ENT_PROD_ID`, `ENTITY_ID`, `ENT_CHG_TYPE`, `ENT_PRORATE`, `ENT_AMT`, `ENT_TX_PER`, `ENT_VR_NR`) VALUES (NULL, '4', '2', 'MRC', 'YES', '100.00', '14.44', NULL);
INSERT INTO `vbass`.`entity_prod_rule` (`ENT_RULE_ID`, `ENT_PROD_ID`, `ENTITY_ID`, `ENT_CHG_TYPE`, `ENT_PRORATE`, `ENT_AMT`, `ENT_TX_PER`, `ENT_VR_NR`) VALUES (NULL, '5', '2', 'NRC', 'NA', '180.00', '14.44', NULL);
INSERT INTO `vbass`.`entity_prod_rule` (`ENT_RULE_ID`, `ENT_PROD_ID`, `ENTITY_ID`, `ENT_CHG_TYPE`, `ENT_PRORATE`, `ENT_AMT`, `ENT_TX_PER`, `ENT_VR_NR`) VALUES (NULL, '6', '2', 'USG', 'NA', '1.20', '14.44', NULL);